---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-log
  labels:
    app.kubernetes.io/instance: demoapp-log
    app.kubernetes.io/name: demoapp-log
spec:
  ports:
  - name: metrics # Default endpoint for querying metrics.
    port: 24231
    protocol: TCP
    targetPort: 24231
  selector:
    app.kubernetes.io/name: demoapp-log
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-log
  labels:
    app.kubernetes.io/instance: demoapp-log
    app.kubernetes.io/name: demoapp-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: demoapp-log
      app.kubernetes.io/name: demoapp-log
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demoapp-log
        app.kubernetes.io/name: demoapp-log
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "24231"
        prometheus.io/scheme: "http"

    spec:
      containers:
        - name: demoapp-log
          image: cdmorgacrrnd.azurecr.io/demoapp/demoapp-log:{{DOCKER_TAG}}
          imagePullPolicy: Always

          command:
            - /app/demoapp.py
            - "--metric-exporter"
            - "prometheus"
            - "--trace-exporter"
            - "otl_collector"
          env:
          - name: OTLP_TRACE_EXPORTER_URL
            valueFrom:
                fieldRef:
                    fieldPath: status.hostIP


