scrape_configs:
  #  - job_name: 'demoapp'
  #  scrape_interval: 5s
  #  static_configs:
  #    - targets: ['demoapp:24231']
  - job_name: 'otel'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:24231']
