extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

processors:
  batch:
  queued_retry:

exporters:
  logging:
    logLevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "testapp"
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true

service:

  extensions: [health_check, pprof, zpages]
  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [logging, zipkin, jaeger]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]

