version: "3.1"
services:
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - example

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - example

  metrics-load-generator:
    container_name: demo
    image: demo-otl-collector-std:latest
    build:
      dockerfile: $PWD/Dockerfile
      context: $PWD
    command: ["/usr/local/bin/main", "-otlagent", "otel-agent:55678"]
    networks:
      - example
    depends_on:
      - otel-agent
      - prometheus
      - jaeger-all-in-one

  otel-agent:
    container_name: agent
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-local-config.yaml"]
    volumes:
      - ./otel-local-config.yaml:/etc/otel-local-config.yaml
    ports:
      - "55679:55679" # zpages extension
      - "55678:55678" # OpenCensus receiver
      - "13133:13133" # health_check
      - "8889:8889"   # Prometheus exporter metrics
      - "8888:8888"   # Prometheus exporter metrics
    depends_on:
      - prometheus
    networks:
      - example

networks:
  example:
